-- passwords are 'a'
insert into users (name, password_hash, email, role_id, enabled) values('owner1', '$2a$10$lO0lamyOi6o9GD2DpzOxUOvo8l7.tTHNKSG1KHXbUD/GEbPxePBhC', 'owner1@owner1', 2, true);
insert into users (name, password_hash, email, role_id, enabled) values('owner2', '$2a$10$lO0lamyOi6o9GD2DpzOxUOvo8l7.tTHNKSG1KHXbUD/GEbPxePBhC', 'owner2@owner2', 2, true);
insert into users (name, password_hash, email, role_id, enabled) values('owner3', '$2a$10$lO0lamyOi6o9GD2DpzOxUOvo8l7.tTHNKSG1KHXbUD/GEbPxePBhC', 'owner3@owner3', 5, true);
insert into users (name, password_hash, email, role_id, enabled) values('bartender1', '$2a$10$lO0lamyOi6o9GD2DpzOxUOvo8l7.tTHNKSG1KHXbUD/GEbPxePBhC', 'bartender1@bartender1', 4, true);
insert into users (name, password_hash, email, role_id, enabled) values('bartender2', '$2a$10$lO0lamyOi6o9GD2DpzOxUOvo8l7.tTHNKSG1KHXbUD/GEbPxePBhC', 'bartender2@bartender2', 5, true);
insert into users (name, password_hash, email, role_id, enabled) values('bartender3', '$2a$10$lO0lamyOi6o9GD2DpzOxUOvo8l7.tTHNKSG1KHXbUD/GEbPxePBhC', 'bartender3@bartender3', 5, true);
insert into users (name, password_hash, email, role_id, enabled) values('user1', '$2a$10$lO0lamyOi6o9GD2DpzOxUOvo8l7.tTHNKSG1KHXbUD/GEbPxePBhC', 'user1@user1', 5, true);
insert into users (name, password_hash, email, role_id, enabled) values('user2', '$2a$10$lO0lamyOi6o9GD2DpzOxUOvo8l7.tTHNKSG1KHXbUD/GEbPxePBhC', 'user2@user2', 5, true);
insert into users (name, password_hash, email, role_id, enabled) values('user3', '$2a$10$lO0lamyOi6o9GD2DpzOxUOvo8l7.tTHNKSG1KHXbUD/GEbPxePBhC', 'user3@user3', 5, true);

insert into business (name, info, icon_url) values('BWW', 'Chicken Wings!', '/img/bars/bww.png');
insert into bar (name, business_id, owner_id, address, city, zipcode, state, phonenumber) values('BWW', (select id from business where name = 'BWW'), (select id from users where name = 'owner1'), '6055 Dryden Road', 'Dryden', '48428', 'MI', '123456789');
insert into barhours (bar_id ,monday ,tuesday ,wednesday ,thursday ,friday ,saturday ,sunday) values((select id from bar where name = 'BWW'), '10-2300','10-2300','10-2300','10-2300','10-2300','10-2300','10-2300');
insert into bartenders (user_id, bar_id) values((select id from users where name = 'bartender1'), (select id from bar where name = 'BWW'));

insert into business (name, info, icon_url) values('Penny Black', 'Good beer and bugers', '/img/bars/pennyblack.png');
insert into bar (name, business_id, owner_id, address, city, zipcode, state, phonenumber) values('Penny Black', (select id from business where name = 'Penny Black'), (select id from users where name = 'owner2'), '6055 Dryden Road', 'Dryden', '48428', 'MI', '123456789');
insert into barhours (bar_id ,monday ,tuesday ,wednesday ,thursday ,friday ,saturday ,sunday) values((select id from bar where name = 'Penny Black'), '10-2300','10-2300','10-2300','10-2300','10-2300','10-2300','10-2300');

insert into ingredient (name, description, icon_url, category_id) values('PBR', 'Cheap Beer', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Coke', 'Coke a cola', '/img/drink_icon/mixer.png', 4);
insert into ingredient (name, description, icon_url, category_id) values('Pepsi', 'Pepsi cola', '/img/drink_icon/mixer.png', 4);
insert into ingredient (name, description, icon_url, category_id) values('Miller Lite', 'Cheap Bear', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Captain Morgan', 'Rum', '/img/drink_icon/liquor.png', 3);
insert into ingredient (name, description, icon_url, category_id) values('Sky Vodka', 'Vodka', '/img/drink_icon/liquor.png', 3);
insert into ingredient (name, description, icon_url, category_id) values('Triple Sec', 'Mixing agent', '/img/drink_icon/mixer.png', 4);
insert into ingredient (name, description, icon_url, category_id) values('Blue Nectar', 'Mid Shelf Tequila', '/img/drink_icon/liquor.png', 3);
insert into ingredient (name, description, icon_url, category_id) values('Tito''s', 'Mid Shelf Vodka', '/img/drink_icon/liquor.png', 3);
insert into ingredient (name, description, icon_url, category_id) values('Bacardi Superior', 'Mid Shelf Rum', '/img/drink_icon/liquor.png', 3);
insert into ingredient (name, description, icon_url, category_id) values('Seagrams Extra Dry', 'Mid Shelf Gin', '/img/drink_icon/liquor.png', 3);
insert into ingredient (name, description, icon_url, category_id) values('Patron Citronge', 'Mid Shelf Triple Sec', '/img/drink_icon/liquor.png', 3);
insert into ingredient (name, description, icon_url, category_id) values('Cola', 'Favorite store brand of Cola.', '/img/drink_icon/mixer.png', 4);
insert into ingredient (name, description, icon_url, category_id) values('Fat Tire', 'Toasty, biscuit-like malt flavors coasting in equilibrium with hoppy freshness.', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Cupcake Prosecco', 'What else is there to say about it?', '/img/drink_icon/wine.png', 2);
insert into ingredient (name, description, icon_url, category_id) values('Michelob Ultra', 'I need an another Ultra! My buzz is starting to wear off.', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Coors Light', 'It''s almost like drinking an avalanche!', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Crabbies Ginger Beer', 'Mildly alcoholic at 4.9%.', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Lime Juice', 'A splash of Lime juice.', '/img/drink_icon/mixer.png', 4);
insert into ingredient (name, description, icon_url, category_id) values('Lime', 'Slice of Lime', '/img/drink_icon/garnish.png', 5);
insert into ingredient (name, description, icon_url, category_id) values('Rebel Grapefruit IPA', 'Samuel Adams Ale brewed with Grapefruit Juice and Hops', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Jack Daniels Rum', 'Mid Shelf Dark Rum', '/img/drink_icon/liquor.png', 3);
insert into ingredient (name, description, icon_url, category_id) values('Tonic Water', 'Plain ol'' Tonic Water', '/img/drink_icon/mixer.png', 4);
insert into ingredient (name, description, icon_url, category_id) values('Guinness Draught', 'Mild Stout brewed by St. James''s Gate Brewery', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Coors Banquet', 'Pilsner brewed by the Coors Brewing Company', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Petite Saison', 'Saison brewed by the Rockmill Brewery', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Pliny The Elder', 'Double Imperial IPA brewed by Russian River Brewing Company', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Blueberry Pancake Milkshake Stout', 'Flavored Milk Stout brewed by Rochester Mills Beer Company', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Organic Wit', 'Organic Wit beer brewed by Rochester Mills Beer Company', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Labatt Blue Light', 'Light Pilsener brewed by Labatt Brewing Company', '/img/drink_icon/beer.png', 1);
insert into ingredient (name, description, icon_url, category_id) values('Labatt Blue', 'Pilsener brewed by Labatt Brewing Company', '/img/drink_icon/beer.png', 1);

-- list of drinks
insert into drink (name, info, make_time, icon_url) values('Coke', 'Coke a cola', 1, '/img/drink_icon/mixer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Coke'), (select id from ingredient where name = 'Coke'));
insert into drink (name, info, make_time, icon_url) values('Kamikaze', 'This is a citrus drink, great for all you lime lovers out there. It is our favorite', 1, '/img/drink_icon/liquor.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Kamikaze'), (select id from ingredient where name = 'Sky Vodka'));
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Kamikaze'), (select id from ingredient where name = 'Triple Sec'));
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Kamikaze'), (select id from ingredient where name = 'Lime Juice'));
insert into drink (name, info, make_time, icon_url) values('Captain Coke', 'Rum & Coke', 1, '/img/drink_icon/liquor.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Captain Coke'), (select id from ingredient where name = 'Coke'));
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Captain Coke'), (select id from ingredient where name = 'Captain Morgan'));
insert into drink (name, info, make_time, icon_url) values('PBR', 'Cheap beer', 1, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'PBR'), (select id from ingredient where name = 'PBR'));
insert into drink (name, info, make_time, icon_url) values('Fat Tire', 'New Belgium Amber Ale', 30, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Fat Tire'), (select id from ingredient where name = 'Fat Tire'));
insert into drink (name, info, make_time, icon_url) values('Cupcake Prosecco', 'Nose of Peach and Nectarine. Soft, creamy Citris accents.', 60, '/img/drink_icon/wine.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Cupcake Prosecco'), (select id from ingredient where name = 'Cupcake Prosecco'));
insert into drink (name, info, make_time, icon_url) values('long island', 'Tequila, Vodka, Light Rum, Gin, Triple Sec, and a splash of Cola.', 120, '/img/drink_icon/mixed.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'long island'), (select id from ingredient where name = 'Blue Nectar'));
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'long island'), (select id from ingredient where name = 'Tito''s'));
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'long island'), (select id from ingredient where name = 'Bacardi Superior'));
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'long island'), (select id from ingredient where name = 'Seagrams Extra Dry'));
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'long island'), (select id from ingredient where name = 'Patron Citronge'));
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'long island'), (select id from ingredient where name = 'Cola'));
insert into drink (name, info, make_time, icon_url) values('Michelob Ultra', 'Superior Light Beer', 30, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Michelob Ultra'), (select id from ingredient where name = 'Michelob Ultra'));
insert into drink (name, info, make_time, icon_url) values('Coors Light', 'Cold as the Rockies', 30, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Coors Light'), (select id from ingredient where name = 'Coors Light'));
insert into drink (name, info, make_time, icon_url) values('Moscow Mule', 'Vodka, Ginger Beer, Lime Juice. Garnished with Lime.', 120, '/img/drink_icon/mixed.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Moscow Mule'), (select id from ingredient where name = 'Tito''s'));
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Moscow Mule'), (select id from ingredient where name = 'Crabbies Ginger Beer'));
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Moscow Mule'), (select id from ingredient where name = 'Lime Juice'));
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Moscow Mule'), (select id from ingredient where name = 'Lime'));
insert into drink (name, info, make_time, icon_url) values('Rebel Grapefruit IPA', 'Samuel Adams Ale brewed with Grapefruit Juice and Hops', 30, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Rebel Grapefruit IPA'), (select id from ingredient where name = 'Rebel Grapefruit IPA'));
insert into drink (name, info, make_time, icon_url) values('Gin and Tonic', 'Gin with a splash of Tonic Water', 45, '/img/drink_icon/mixed.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Gin and Tonic'), (select id from ingredient where name = 'Seagrams Extra Dry'));
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Gin and Tonic'), (select id from ingredient where name = 'Tonic Water'));
insert into drink (name, info, make_time, icon_url) values('Guinness Draught', 'Mild Stout brewed by St. James''s Gate Brewery', 30, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Guinness Draught'), (select id from ingredient where name = 'Guinness Draught'));
insert into drink (name, info, make_time, icon_url) values('Coors Banquet', 'For when you''re fine with consuming a few extra calories', 30, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Coors Banquet'), (select id from ingredient where name = 'Coors Banquet'));
insert into drink (name, info, make_time, icon_url) values('Petit Saison', 'Nice saison by Rockmill Brewery, with a 5.6% ABV.', 30, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Petit Saison'), (select id from ingredient where name = 'Petit Saison'));
insert into drink (name, info, make_time, icon_url) values('Pliny The Elder', 'Double Imperial IPA not meant to be saved for special occasions.', 30, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Pliny The Elder'), (select id from ingredient where name = 'Pliny The Elder'));
insert into drink (name, info, make_time, icon_url) values('Blueberry Pancake Milkshake Stout', 'The Supreme Emperor of breakfast beers. Brewed by Rochester Mills Beer Company', 30, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Blueberry Pancake Milkshake Stout'), (select id from ingredient where name = 'Blueberry Pancake Milkshake Stout'));
insert into drink (name, info, make_time, icon_url) values('Organic Wit', 'Organic Wit Beer. Brewed by Rochester Mills Beer Company', 30, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Organic Wit'), (select id from ingredient where name = 'Organic Wit'));
insert into drink (name, info, make_time, icon_url) values('Labatt Blue Light', 'If it ain''t Labatt, it ain''t Labatt.', 30, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Labatt Blue Light'), (select id from ingredient where name = 'Labatt Blue Light'));
insert into drink (name, info, make_time, icon_url) values('Labatt Blue', 'Full bodied Pilsener, full of Canadian goodness.', 30, '/img/drink_icon/beer.png');
    insert into drink_ingredients (drink_id, ingredient_id) values((select id from drink where name = 'Labatt Blue'), (select id from ingredient where name = 'Labatt Blue'));

-- drinks for BWW
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'Coke'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'Captain Coke'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'PBR'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'long island'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'Michelob Ultra'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'Coors Light'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'Moscow Mule'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'Kamikaze'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'Fat Tire'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'Cupcake Prosecco'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'Guinness Draught'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'Labatt Blue'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'Labatt Blue Light'), (select id from bar where name = 'BWW'), 3.50);
insert into availabledrinks (drink_id, bar_id, price) values((select id from drink where name = 'Rum and Cola'), (select id from bar where name = 'BWW'), 3.50);
